name: ML
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - jupyter
  - tqdm
  - ipykernel
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - pip:
    - kaggle
